// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgw-sfjMVggvlQjM93LmPABJOI_yNGDIA',
    appId: '1:932194445968:web:b3ed141673bece361c8615',
    messagingSenderId: '932194445968',
    projectId: 'project-7d094',
    authDomain: 'project-7d094.firebaseapp.com',
    storageBucket: 'project-7d094.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1Z9fpNZK7OX7r7XGHKp3_gHi-r3CfZA',
    appId: '1:932194445968:android:4094e9278aa4db551c8615',
    messagingSenderId: '932194445968',
    projectId: 'project-7d094',
    storageBucket: 'project-7d094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQTxcNgQvv6E0KUReQ45UvprPxGakVsI',
    appId: '1:932194445968:ios:7d0741cff76a1fa81c8615',
    messagingSenderId: '932194445968',
    projectId: 'project-7d094',
    storageBucket: 'project-7d094.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );
}
